[package]
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]
name = "railroad"
version = "0.1.0"

[dependencies]
blake2 = "0.7.0"
clap = "2.29.2"
curve25519-dalek = "0.14.4"
ed25519-dalek = "0.6.1"
env_logger = "0.5.2"
fnv = "1.0.6"
futures = "0.1.17"
log = "0.4.1"
rand = "0.4.2"
tokio-core = "0.1.12"
tokio-timer = "0.1.2"
num-traits = "0.1.41"
num-bigint = "0.1.41"

[dependencies.byteorder]
features = ["i128"]
version = "1.2.1"

[dependencies.digest]
features = ["std"]
version = "0.7.2"
