[package]
name = "nanocurrency-protocol"
version = "0.4.0"
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]
description = "Protocol code for the Nano cryptocurrency"
license = "BSD-2-Clause"

[dependencies]
byteorder = { version = "1", features = ["i128"] }
bytes = "0.4"
tokio-io = "0.1"
nanocurrency-types = { version = "0.3", path = "../nanocurrency-types" }
