[package]
name = "nanocurrency-protocol"
version = "0.5.1"
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]
description = "Protocol code for the Nano cryptocurrency"
license = "BSD-2-Clause"
repository = "https://github.com/PlasmaPower/railroad"

[dependencies]
byteorder = { version = "1", features = ["i128"] }
bytes = "0.4"
tokio-io = "0.1"
nanocurrency-types = { version = "0.3.6", path = "../nanocurrency-types" }
